Kenny Lu
Assignment 2


Smithy Card - The smithy card is located in the dominion.h file as an enum alongside the other possible cards in the game. In dominion.c, the smithy card is located in a series of switch statements that are used in selecting cards as well as performing actions in the game. When the code for case smithy runs, the drawCard function is called in a loop 3 times which effectively draws 3 cards. The smithy card is also found in the getCost functions which defines the card as having a cost of 4. 

Adventurer Card - The adventurer card is also located in the dominion.h file as an enum of possible cards. In dominion.c, the adventurer card is defined as having 6 cost within the getCost function. The adventurer case will draw cards in a while loops while the count for drawn treasure is less than 2. Everytime some sort of treasure is drawn, the counter for drawn treasure increases. If the card drawn is not a treasure, it is discarded in an else statement.

discardCard() - This function takes in four parameters which includes Handpos, CurrentPlayer, gameState *state, and trashFlag. Handpos keeps track of the index of where the card to be discarded is. CurrentPlayer takes into account which player is to discard the card. Gamestate *state keeps track of which phase the gamee is in at the current moment. Lastly, trashFlag determines where the discarded card will go which would either be the played pile or discarded pile. Before calling this function, the card to be discarded should be somewhere in the player's hand. The function looks at the trash flag and adds the card to the played pile if the value is less than 1. The played card is then set to -1 and is removed from the player's hand. If either the last card is played or there is only 1 card in hand, then number of cards in hand decrements. If none of the previous conditions are met, then the function replaces the discarded card with last card in hand before reducing number of cards in hand.

updateCoins() - This function takes in 3 parameters which includes int player, GameState *state, and int bonus. The first parameter keeps track of which player the function is updating, the second represents the game state, while the last determines the amount of coins received from action cards. The function resets the coin count for that particular player and then adds up each treasure card based on its value from the player's hand. Bonuses are then added in afterwards. 